site:
  language: en
  title: "PHPoole"
  baseline: "Redirections from phpoole.org to cecil.app."
  baseurl: https://phpoole.org/
  description: "Redirections from phpoole.org to cecil.app."
  author:
    name: Arnaud Ligny
    url: https://arnaudligny.fr
  fmpages:
    redirects:
      layout: _redirects.txt
      permalink: _redirects
    index:
      permalink: /
      redirect: https://cecil.app
    documentation:
      redirect: https://cecil.app/documentation
    documentation/quick-start:
      redirect: https://cecil.app/documentation/quick-start
    documentation/pages:
      redirect: https://cecil.app/documentation/pages
    documentation/layouts:
      redirect: https://cecil.app/documentation/layouts
    documentation/configuration:
      redirect: https://cecil.app/documentation/configuration
    documentation/library:
      redirect: https://cecil.app/documentation/library
    download:
      redirect: https://cecil.app/download
    about:
      redirect: https://cecil.app/about
