site:
  language: en
  title: "PHPoole"
  baseline: "Redirections from phpoole.org to cecil.app."
  baseurl: https://phpoole.org/
  description: "Redirections from phpoole.org to cecil.app."
  author:
    name: Arnaud Ligny
    url: https://arnaudligny.fr
  fmpages:
    index:
      permalink: /
      redirect: https://cecil.app
    documentation:
      redirect: https://cecil.app/documentation
    download:
      redirect: https://cecil.app/download
    about:
      redirect: https://cecil.app/about
